<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Profil_Radusergroup extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Profil_Radusergroup_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','profil_radusergroup/radusergroup_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Profil_Radusergroup_model->json();
    }

    public function read($id) 
    {
        $row = $this->Profil_Radusergroup_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_group' => $row->id_group,
		'username' => $row->username,
		'groupname' => $row->groupname,
		'priority' => $row->priority,
	    );
            $this->template->load('template','profil_radusergroup/radusergroup_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('profil_radusergroup'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('profil_radusergroup/create_action'),
	    'id_group' => set_value('id_group'),
	    'username' => set_value('username'),
	    'groupname' => set_value('groupname'),
	    'priority' => set_value('priority'),
	);
        $this->template->load('template','profil_radusergroup/radusergroup_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'username' => $this->input->post('username',TRUE),
		'groupname' => $this->input->post('groupname',TRUE),
		'priority' => $this->input->post('priority',TRUE),
	    );

            $this->Profil_Radusergroup_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('profil_radusergroup'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Profil_Radusergroup_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('profil_radusergroup/update_action'),
		'id_group' => set_value('id_group', $row->id_group),
		'username' => set_value('username', $row->username),
		'groupname' => set_value('groupname', $row->groupname),
		'priority' => set_value('priority', $row->priority),
	    );
            $this->template->load('template','profil_radusergroup/radusergroup_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('profil_radusergroup'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_group', TRUE));
        } else {
            $data = array(
		'username' => $this->input->post('username',TRUE),
		'groupname' => $this->input->post('groupname',TRUE),
		'priority' => $this->input->post('priority',TRUE),
	    );

            $this->Profil_Radusergroup_model->update($this->input->post('id_group', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('profil_radusergroup'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Profil_Radusergroup_model->get_by_id($id);

        if ($row) {
            $this->Profil_Radusergroup_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('profil_radusergroup'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('profil_radusergroup'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('username', 'username', 'trim|required');
	$this->form_validation->set_rules('groupname', 'groupname', 'trim|required');
	$this->form_validation->set_rules('priority', 'priority', 'trim|required');

	$this->form_validation->set_rules('id_group', 'id_group', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Profil_Radusergroup.php */
/* Location: ./application/controllers/Profil_Radusergroup.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-01 22:07:30 */
/* http://harviacode.com */