<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_status_model extends CI_Model
{

    public $table = 'user_status';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,radacct_id,username,nasipaddress,framedipaddress,callingstationid,timestamp,acctinputoctets,acctoutputoctets');
        $this->datatables->from('user_status');
        //add this line for join
        //$this->datatables->join('table2', 'user_status.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('user_status/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('user_status/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('user_status/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('radacct_id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('nasipaddress', $q);
	$this->db->or_like('framedipaddress', $q);
	$this->db->or_like('callingstationid', $q);
	$this->db->or_like('timestamp', $q);
	$this->db->or_like('acctinputoctets', $q);
	$this->db->or_like('acctoutputoctets', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('radacct_id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('nasipaddress', $q);
	$this->db->or_like('framedipaddress', $q);
	$this->db->or_like('callingstationid', $q);
	$this->db->or_like('timestamp', $q);
	$this->db->or_like('acctinputoctets', $q);
	$this->db->or_like('acctoutputoctets', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_status_model.php */
/* Location: ./application/models/User_status_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-02 01:40:44 */
/* http://harviacode.com */